from support_agent.tools.schemas import (
    CREATE_TICKET_TOOL,
    ESCALATE_TO_HUMAN_TOOL,
    KNOWLEDGE_BASE_SEARCH_TOOL,
    SEARCH_SIMILAR_TICKETS_TOOL,
)


RESEARCH_AGENT_TOOLS = [
    SEARCH_SIMILAR_TICKETS_TOOL,
]


SUPPORT_AGENT_TOOLS = [
    KNOWLEDGE_BASE_SEARCH_TOOL,
    CREATE_TICKET_TOOL,
    ESCALATE_TO_HUMAN_TOOL,
]